### ISSUE TITLE
Preview returns "ReferenceError: Cannot access 'serverQrl' before initialization" 

### ISSUE THREAD

**Issue by ar1em-k** [vendure-ecommerce/storefront-qwik-starter#124] opened 2023-08-06 21:06 UTC
Npm/Yarn start works fine, but when trying to run "preview" (and disabling minification so error is not gibberish) I'm getting "ReferenceError: Cannot access 'serverQrl' before initialization".

Almost every instance of serverQrl is in autogenerated js files so it's either a qwik/npm bug (Unlikely - everything worked fine when I tried running "preview" on the example qwik app), a problem with configuration, or a problem with adding qwik's lazy-loading where it doesn't fit, 

P.S. This is the first qwik app I'm trying, so I'm not sure what else should I check for a better bug report (if you need more info, please say what I need to send)

**Comment by gioboa** [comment] 2023-08-07 11:05
Can you describe the steps to reproduce the issue?

**Comment by ar1em-k** [comment] 2023-08-07 22:07
@gioboa  For me it was
1. run `npm run preview`
2. open the browser
3. See "ReferenceError: Cannot access 'Gy' before initialization" ![Screenshot_2023-08-08-00-25-49_1920x1080](https://github.com/vendure-ecommerce/storefront-qwik-starter/assets/128474238/e656ad1b-4ea6-49d9-887e-030f1dddf5bd)
4. add 	`minify:false` option to build options of vite.config.ts
5. See the real message of "ReferenceError: Cannot access 'serverQrl' before initialization"
![Screenshot_2023-08-08-00-31-19_1920x1080](https://github.com/vendure-ecommerce/storefront-qwik-starter/assets/128474238/710254cb-98e3-4397-96d2-3f83cdbb260e)
Terminal running the command doesn't have any additional info.
![Screenshot_2023-08-08-00-41-44_1920x1080](https://github.com/vendure-ecommerce/storefront-qwik-starter/assets/128474238/54de32b0-1fa5-4453-93d1-0c106a57e5c3)
(Even defining CustomLogger in vite.config.ts (that replaces everything with console.trace), does not give more info on error
![Screenshot_2023-08-08-01-03-34_1920x1080](https://github.com/vendure-ecommerce/storefront-qwik-starter/assets/128474238/6d3d87c0-382b-49db-90dd-7a64d16e3958) )


P.S. Now double checking git I've noticed that package-lock.json is changed compared to the state I pulled the repo yesterday. Deleting in and running `npm i`  again doesn't revert it to a state it was in git. Possibly one of the updates could break something in server. Just in case I created a git patch from all the changes compared to the git (I doubt autogenerated graphql schemas may be the problem, but better safe than sorry)
[changes_compared_to_default.patch.txt](https://github.com/vendure-ecommerce/storefront-qwik-starter/files/12285352/changes_compared_to_default.patch.txt)

**Comment by gioboa** [comment] 2023-08-14 12:09
Fixed with [this commit](https://github.com/vendure-ecommerce/storefront-qwik-starter/commit/517d6313fe41722e8fdcee85951b4802778d44e0)
btw I will investigate more to update the lib.

**Comment by gioboa** [comment] 2023-08-14 12:09
@ar1em-k Thanks for your report 👍

**Comment by gioboa** [comment] 2023-08-15 20:08
The problem seems to be there, I will investigate

**Comment by gioboa** [comment] 2023-08-16 10:05
With Qwik 1.1.6 preview works, but with Qwik 1.2.0+ we have the issue. We only have one server$ function but even if we removed it the problem persists. I think could be a dependency clash with vite

**Comment by gioboa** [comment] 2023-08-16 20:11
it's really odd, now `preview` is working 🤷‍♂️

**Closed by gioboa** 2023-08-16 20:11 UTC
