### ISSUE TITLE
once user logged in, his mail appeared in the search bar

### ISSUE THREAD

**Issue by redaready** [vendure-ecommerce/storefront-qwik-starter#82] opened 2023-03-29 06:02 UTC
"Password change" and "Account details" have this strange behavior
https://qwik-storefront.vendure.io/account/
https://qwik-storefront.vendure.io/account/password/

<img width="554" alt="chrome_lLcTaOe7vY" src="https://user-images.githubusercontent.com/116800/228439810-cb263e8a-0068-43ce-a0bb-868be119222a.png">

**Comment by gioboa** [comment] 2023-03-29 06:07
I see, thanks for the feedback, we will solve it

**Comment by gioboa** [comment] 2023-03-29 15:34
I can't reproduce the problem. can you record a video pls?

**Comment by redaready** [comment] 2023-03-30 01:54
i tested https://qwik-storefront.vendure.io/ with latest chrome, firefox, edge, they all have same problem. but with brave, everything is fine..chrome ingonito mode works fine too. 

a important note: you must save the password in browser password manager to reproduce this problem, apperently once password saved in the password manager, the user's email will appear in the search box once you click tabs "Password change" and "Account details" 
https://user-images.githubusercontent.com/116800/228706288-639583da-32b9-4475-ae82-b69d6b79ab71.mp4

**Comment by gioboa** [comment] 2023-03-30 05:37
I merged your PR. If it's solved, we can close the issue

**Comment by redaready** [comment] 2023-03-30 05:58
yes, let's close it

**Comment by gioboa** [comment] 2023-04-13 06:22
#90 fixed it

**Closed by gioboa** 2023-04-13 06:22 UTC
